config/routes.rb
Rails.application.routes.draw do
  resources :eletronics
  resources :users
  resources :brands
  resources :service_orders
  root "home#index"
end

app/models/service_order.rb
class ServiceOrder < ApplicationRecord
  has_one :eletronic
  belongs_to :user
end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  before_action :set_service_order, only: %i[ show edit update destroy ]

  # GET /service_orders or /service_orders.json
  def index
    @service_orders = ServiceOrder.all
  end

  # GET /service_orders/1 or /service_orders/1.json
  def show
  end

  # GET /service_orders/new
  def new
    @service_order = ServiceOrder.new
  end

  # GET /service_orders/1/edit
  def edit
  end

  # POST /service_orders or /service_orders.json
  def create
    @service_order = ServiceOrder.new(service_order_params)

    respond_to do |format|
      if @service_order.save
        format.html { redirect_to @service_order, notice: "Service order was successfully created." }
        format.json { render :show, status: :created, location: @service_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_orders/1 or /service_orders/1.json
  def update
    respond_to do |format|
      if @service_order.update(service_order_params)
        format.html { redirect_to @service_order, notice: "Service order was successfully updated." }
        format.json { render :show, status: :ok, location: @service_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_orders/1 or /service_orders/1.json
  def destroy
    @service_order.destroy!

    respond_to do |format|
      format.html { redirect_to service_orders_path, status: :see_other, notice: "Service order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_order
      @service_order = ServiceOrder.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def service_order_params
      params.expect(service_order: [ :user_id, :service_order_number, :reported_issue, :identified_issue, :obs ])
    end
end

app/helpers/service_orders_helper.rb
module ServiceOrdersHelper
end

app/views/service_orders/_form.html.erb
<%= form_with(model: service_order, class: "contents") do |form| %>
  <% if service_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(service_order.errors.count, "error") %> prohibited this service_order from being saved:</h2>

      <ul>
        <% service_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :cliente %>
    <%= form.select :user_id, User.order(:name).map { | user | [user.name, user.id] } , class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :numero_da_os %>
    <%= form.text_field :service_order_number, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :defeito_relatado_pelo_cliente %>
    <%= form.text_field :reported_issue, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :defeito_identificado %>
    <%= form.text_field :identified_issue, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :obs %>
    <%= form.text_field :obs, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/service_orders/_service_order.html.erb
<div id="<%= dom_id service_order %>" class="flex ">
  <p class="my-5">
    <strong class="block font-medium mb-1">Cliente:</strong>
    <%= service_order.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Numero da O.S.:</strong>
    <%= service_order.service_order_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Problema Identificado:</strong>
    <%= service_order.identified_issue %>
  </p>

</div>

app/views/service_orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing service order</h1>

  <%= render "form", service_order: @service_order %>

  <%= link_to "Show this service order", @service_order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to service orders", service_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/service_orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Service orders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ordens de Serviço</h1>
    <%= link_to "Criar Nova O.S.", new_service_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="service_orders" class="min-w-full">
    <% @service_orders.each do |service_order| %>
      <%= render service_order %>
      <p>
        <%= link_to "Mostrar", service_order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/service_orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova Ordem de Serviço</h1>

  <%= render "form", service_order: @service_order %>

  <%= link_to "Voltar", service_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/service_orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @service_order %>

    <%= link_to "Edit this service order", edit_service_order_path(@service_order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to service orders", service_orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this service order", @service_order, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>