config/routes.rb
Rails.application.routes.draw do
  resources :eletronics
  resources :users
  resources :brands
  resources :service_orders
  root "home#index"
end

app/models/eletronic.rb
class Eletronic < ApplicationRecord
  belongs_to :service_order, optional: true
end

app/models/eletronic_type.rb
class EletronicType < ApplicationRecord
  belongs_to :eletronic
end

app/controllers/eletronics_controller.rb
class EletronicsController < ApplicationController
  before_action :set_eletronic, only: %i[ show edit update destroy ]

  # GET /eletronics or /eletronics.json
  def index
    @eletronics = Eletronic.all
  end

  # GET /eletronics/1 or /eletronics/1.json
  def show
  end

  # GET /eletronics/new
  def new
    @eletronic = Eletronic.new
  end

  # GET /eletronics/1/edit
  def edit
  end

  # POST /eletronics or /eletronics.json
  def create
    if EletronicType.find(:type_id)
      @eletronic = Eletronic.new(eletronic_params)

      respond_to do |format|
        if @eletronic.save
          format.html { redirect_to @eletronic, notice: "Eletronic was successfully created." }
          format.json { render :show, status: :created, location: @eletronic }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @eletronic.errors, status: :unprocessable_entity }
        end
      end
    else
      @type = EletronicType.new(:type_id)

      @eletronic = Eletronic.new(eletronic_params)

      respond_to do |format|
        if @eletronic.save
          format.html { redirect_to @eletronic, notice: "Eletronic was successfully created." }
          format.json { render :show, status: :created, location: @eletronic }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @eletronic.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /eletronics/1 or /eletronics/1.json
  def update
    respond_to do |format|
      if @eletronic.update(eletronic_params)
        format.html { redirect_to @eletronic, notice: "Eletronic was successfully updated." }
        format.json { render :show, status: :ok, location: @eletronic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @eletronic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eletronics/1 or /eletronics/1.json
  def destroy
    @eletronic.destroy!

    respond_to do |format|
      format.html { redirect_to eletronics_path, status: :see_other, notice: "Eletronic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eletronic
      @eletronic = Eletronic.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def eletronic_params
      params.expect(eletronic: [ :serial_number, :model, :quantity, :color, :type_id, :accessory_id, :brand_id ])
    end
end

app/helpers/eletronics_helper.rb
module EletronicsHelper
end

app/views/eletronics/_eletronic.html.erb
<div id="<%= dom_id eletronic %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Serial number:</strong>
    <%= eletronic.serial_number %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Model:</strong>
    <%= eletronic.model %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= eletronic.quantity %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Color:</strong>
    <%= eletronic.color %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= eletronic.type_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Accessory:</strong>
    <%= eletronic.accessory_id %>
  </p>

</div>

app/views/eletronics/_form.html.erb
<%= form_with(model: eletronic, class: "contents") do |form| %>
  <% if eletronic.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(eletronic.errors.count, "error") %> prohibited this eletronic from being saved:</h2>

      <ul>
        <% eletronic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :Número_de_série %>
    <%= form.text_field :serial_number, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :modelo %>
    <%= form.text_field :model, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantidade %>
    <%= form.text_field :quantity, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cor %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <% if EletronicType.any? %>
    <%= form.label :tipo_de_eletrônico %>
    <%= form.select :type_id, EletronicType.order(:name).map { |type| [type.name, type.id] },class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  <% end %>
  </div>

  <div class="my-5">
    <%= form.label :tipo_de_eletrônico %>
    <%= form.text_field :type_id, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :acessório %>
    <%= form.select :accessory_id, Accessory.order(:name).map { |accessory| [accessory.name, accessory.id] }, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex items-center justify-between my-5">
      <%= form.label :marca %>
    <div>
      <%= form.text_field :brand_name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="grow ">
      <% if Brand.any? %>
        <%= form.select :brand_id, Brand.order(:name).map { |brand| [brand.name, brand.id] }, class: "shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
      <% end %>
    </div>

    <%= javascript_include_tag 'dynamic_select' %>

  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<
<% end %>

app/views/eletronics/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing eletronic</h1>

  <%= render "form", eletronic: @eletronic %>

  <%= link_to "Show this eletronic", @eletronic, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to eletronics", eletronics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/eletronics/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Eletronics" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Equipamentos</h1>
    <%= link_to "Adicionar", new_eletronic_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="eletronics" class="min-w-full">
    <% @eletronics.each do |eletronic| %>
      <%= render eletronic %>
      <p>
        <%= link_to "Mostrar", eletronic, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/eletronics/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Adicionar Novo Eletrônico</h1>

  <%= render "form", eletronic: @eletronic %>

  <%= link_to "Back to eletronics", eletronics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/eletronics/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @eletronic %>

    <%= link_to "Edit this eletronic", edit_eletronic_path(@eletronic), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to eletronics", eletronics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this eletronic", @eletronic, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>